version: '3'

services:
  goravel:
    container_name: goravel-api
    build:
      context: .
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
  
  db:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'goravel'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
